# My variables
name: tang1943
description: programing, dataming
google_verification: null
category_dir: categories
collection_name: blog_posts


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
      block:
        line_numbers: true
        start_line: 1
 
collections:
  - blog_posts

collections:
  blog_posts:
    output: true
    permalink: /posts/:path/

defaults:
  - scope:
      path: ""
      type: "blog_posts"
    values:
      layout: default

