# My variables
name: tang1943
description: programing, dataming
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
 
#highlight: true
highlighter: rouge

collections:
  - blog_posts

collections:
  blog_posts:
    outputs: true
    permalink: /posts/:path/

defaults:
  - scope:
      path: ""
      type: "blog_posts"
    values:
      layouts: page
